export const LOGINREQ = "LOGINREQ"
export const LOGINSUCCESS = "LOGINSUCCESS"
export const LOGINFAILURE = "LOGINFAILURE"

export const PROJECTFORMPRIMAGESREQ     = "PROJECTFORMPRIMAGESREQ";
export const PROJECTFORMPRIMAGESSUCESS  = "PROJECTFORMPRIMAGESSUCESS";
export const PROJECTFORMPRIMAGESFAILURE = "PROJECTFORMPRIMAGESFAILURE";

export const UPDATEDIMAGESAWS_DATA_REQUEST = "UPDATEDIMAGESAWS_DATA_REQUEST";
export const UPDATEDIMAGESAWS_DATA_SUCESS  = "UPDATEDIMAGESAWS_DATA_SUCESS";
export const UPDATEDIMAGESAWS_DATA_FAILURE = "UPDATEDIMAGESAWS_DATA_FAILURE";

